dist: trusty
language: scala
scala:
- 2.12.2
jdk:
- openjdk8
script:
  - sbt test
deploy:
  - provider: script
    script: 
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - sbt docker:publish 
    skip_cleanup: true
    on:
      tags: true
