dist: trusty
language: scala
scala:
- 2.12.2
jdk:
- openjdk8
script:
- sbt test
deploy:
- provider: script
  script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - sbt docker:publish
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: CInuuQEHT/apu/2t1JEI0TqifiGaUK/FwhYsNa3aUL+/fZQ84KKVlZIrD2FmAXuc8VRsM58SSRtR7MvZHqbAIPGDc3p0uojpVanRztIKfpxZCTve8qWKAhqh1BF1HfAXU1H7LAjCjEARfwtXctoNNtBx6OUxq64ssLpwqzydEbqTlApJy1AnrGYY+JuKu9SsZoLxe94A/+EgyczYnauWR8FxP8SDUb+r+DPeO1bAoU8bbpI4jzJH6IaJ4UAuybRPHjvOo+7cK/VGP6rpMD6/XwX0+61dnd8Sq9rQs2pLURA5GXYSewBgvfDCsUf0/iK9d3hEWkHBUs+KeOeNEM1E7s8dXvHEzzMRXrIvcG5BuMihXjMJb0XqKN0TBW6VYKc9KY+KmEH1ZQ80y8kvGFRUuYhwrFmcgPSSvm7s96pzsBkXVSvRfTGMzcXhc71RHtY7DGeGex2ibezV1cpXD88EPZKn+ksK8XUgH7mJO3iyQn/5+8gc6fuJvjPuchq11jn4nfwrlEzx56se8Uhg/5GuCGqXp0dyJ47AjmjIYmxLuCkyuYPRw2p9mAjk2DWDeqBoYtvPQ55RBfJusC6MFN33+S8uSvTiaYNLbQKSdlPW14Xkbcis2QJHVbwreHc/3VgIpSTM2hmrKIw1C/R4hO7FDvCH9HN+pZ2DlvhAimaNbgY=
  - secure: K4E2YGNkKN7I1XIXAxnhMGyFy9MmQr+Kf/Aul6qpIPiDhe05Mo4PdbX94ICEN/GAyzf5r2f1ddLeju1N0lKAY45P15Yo5aPkZG/t6/ZGoSWqKleS/CI/8TUsJi/v4oNbT937mOdE1/cFnQX8ur+F3xua+kMSNdIGuHT/sHk+HGxcqORXlzE/oqh0GXoBgWXf0vxUKGUXQEgNSpVORWk6bhDUm1G3sLer1YSWYFr4gpF0TOgc4tbwSskYoljnI7i7pTCGmzPkAtoSZpEnbiSn+CZugb+TVTlF9CUysTpwBZ0MK5xp/LfFWwjQW2x1AOzOQltZUR+cDykaAGkWWUks4Tm2+CGiMS0Y5vsTqgXsZ4smG2LSZ9s/VqXnNIfJVDn55S3kRr+v5Xx4EHDoTN4LlTbIjFijzATCrZ8+HlKNPmgRYTG/o+zSMfGjRTp7q1KifirnHi3g9idrSFVLR/1ZGBzBKfV/RGGLWtS5bjzte2qLwImEW1jJFz61w/IxYi12/+OZLXtPUYplytH4czTHr52F1ONErPxcGVfgDOaNYXwPdhrgXNloCn2EcQK2Kiao/s8DvCd3vdbb3oWsQNrKp/u1SZ+wr9yqpDHnK8eXHXGw3EgRAcMXgVKtvq7/fRxilUdWwqF+xmcLjamAeXzbChVt2e/WCKoD3OFIG356r7U=
